sonar.projectKey=SIDERAE-Blenkir
sonar.projectName=SIDERAE-Blenkir
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

sonar.sources=backend/app,backend/routes,backend/database,frontend/src,ml-service
sonar.tests=backend/tests,frontend/cypress

sonar.exclusions=**/node_modules/**,**/vendor/**,**/storage/**,**/bootstrap/cache/**,**/public/build/**,**/dist/**,**/build/**,**/coverage/**,**/.vite/**,**/.next/**,**/__pycache__/**,**/*.log,**/docs/evidencias/**,**/cypress/screenshots/**,**/cypress/videos/**,**/docker/mysql_data/**,**/mysql_data/**,**/docker/**/mysql_data/**,**/*.ibd,**/#innodb_redo/**

sonar.test.inclusions=backend/tests/**/*.php,frontend/cypress/e2e/**/*.js
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.php.coverage.reportPaths=backend/coverage.xml
